name: go
description: Simplest API to multi process.
version: 1.0.0
homepage: https://github.com/desktop-dart/go.dart
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
