name: go
description: Simplest API to multi process using isolates.
version: 1.0.6
homepage: https://github.com/desktop-dart/go.dart
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  async: ^1.13.3

dev_dependencies:
  test: ^0.12.0
